# Generated by Django 4.2.20 on 2025-05-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoursApp', '0004_remove_customer_password_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
